import {
  Holding,
  MarketIndex,
  MarketPulse,
  NewsArticle,
  PricePoint,
  SectorPerformance,
  StockProfile,
  TopMover,
  type CryptoQuote,
  type FixedIncomeRow,
  type FuturesAsset,
  type MarketMovers,
  type MarketSummaryBlock,
  type PopularSpace,
  type RecentDevelopment,
  type SectorEtfRow,
  type StandoutStock,
  type WatchlistBarEntry,
} from "@/types/finance";

function series(values: number[]): PricePoint[] {
  return values.map((price, index) => ({
    label: `${9 + Math.floor(index / 2)}:${index % 2 === 0 ? "30" : "45"}`,
    price,
    volume: 800_000 + index * 125_000,
  }));
}

function quoteStub(
  symbol: string,
  name: string,
  price: number,
  changePercent: number,
  exchange: string,
  sector: string,
): StockProfile {
  const change = (price * changePercent) / 100;

  return {
    symbol,
    name,
    price,
    change,
    changePercent,
    marketCap: 0,
    sector,
    industry: "—",
    exchange,
    peRatio: 0,
    dividendYield: 0,
    week52Low: price * 0.92,
    week52High: price * 1.08,
    volume: 1_200_000,
    averageVolume: 1_000_000,
    beta: 1,
    description: `${name} provides benchmark exposure for asset allocation and tactical trades.`,
    thesis: "Macro conditions, sector rotation, and fund flows influence relative performance.",
    chart: series(
      Array.from({ length: 12 }, (_, index) => price * (1 + (index - 5.5) * 0.0008)),
    ),
  };
}

function listedInstruments(): StockProfile[] {
  return [
    quoteStub("XLK", "Technology Select Sector SPDR Fund", 135.29, -2.27, "ARCA", "ETFs"),
    quoteStub("XLE", "Energy Select Sector SPDR Fund", 59.31, -0.08, "ARCA", "ETFs"),
    quoteStub("XLY", "Consumer Discretionary Select Sector SPDR Fund", 107.74, -1.79, "ARCA", "ETFs"),
    quoteStub("XLP", "Consumer Staples Select Sector SPDR Fund", 81.29, -0.83, "ARCA", "ETFs"),
    quoteStub("XLC", "Communication Services Select Sector SPDR Fund", 112.23, -0.8, "ARCA", "ETFs"),
    quoteStub("XLI", "Industrial Select Sector SPDR Fund", 161.67, -1.46, "ARCA", "ETFs"),
    quoteStub("XLF", "Financial Select Sector SPDR Fund", 49.08, -0.18, "ARCA", "ETFs"),
    quoteStub("XLU", "Utilities Select Sector SPDR Fund", 44.65, -4.06, "ARCA", "ETFs"),
    quoteStub("XLB", "Materials Select Sector SPDR Fund", 46.98, -1.59, "ARCA", "ETFs"),
    quoteStub("XLRE", "Real Estate Select Sector SPDR Fund", 40.59, -3.17, "ARCA", "ETFs"),
    quoteStub("XLV", "Health Care Select Sector SPDR Fund", 145.33, -0.87, "ARCA", "ETFs"),
    quoteStub("BTCUSD", "Bitcoin / U.S. Dollar", 68_292, -2.96, "CRYPTO", "Cryptocurrencies"),
    quoteStub("ETHUSD", "Ethereum / U.S. Dollar", 2066.8, -3.96, "CRYPTO", "Cryptocurrencies"),
    quoteStub("SOLUSD", "Solana / U.S. Dollar", 87.05, -3.07, "CRYPTO", "Cryptocurrencies"),
    quoteStub("XRPUSD", "XRP / U.S. Dollar", 1.39, -3.38, "CRYPTO", "Cryptocurrencies"),
    quoteStub("TIP", "iShares TIPS Bond ETF", 110.22, -0.8, "ARCA", "Fixed Income"),
    quoteStub("GOVT", "iShares U.S. Treasury Bond ETF", 22.79, -0.72, "ARCA", "Fixed Income"),
    quoteStub("MUB", "iShares National Muni Bond ETF", 105.91, -0.88, "ARCA", "Fixed Income"),
    quoteStub("CWB", "SPDR Bloomberg Convertible Securities ETF", 91.98, -2.26, "ARCA", "Fixed Income"),
    quoteStub("HYG", "iShares iBoxx $ High Yield Corporate Bond ETF", 78.92, -0.93, "ARCA", "Fixed Income"),
    quoteStub("LQD", "iShares iBoxx $ Investment Grade Corporate Bond ETF", 107.85, -1.23, "ARCA", "Fixed Income"),
  ];
}

export const marketIndices: MarketIndex[] = [
  {
    symbol: "SPX",
    name: "S&P 500",
    price: 5176.42,
    displayValue: "5,176.42",
    change: 38.22,
    displayChange: "+38.22",
    changePercent: 0.74,
    sessionRange: "5,128 - 5,184",
  },
  {
    symbol: "NDX",
    name: "Nasdaq 100",
    price: 18221.65,
    displayValue: "18,221.65",
    change: -44.81,
    displayChange: "-44.81",
    changePercent: -0.25,
    sessionRange: "18,188 - 18,336",
  },
  {
    symbol: "DJI",
    name: "Dow Jones",
    price: 39184.6,
    displayValue: "39,184.60",
    change: 164.22,
    displayChange: "+164.22",
    changePercent: 0.42,
    sessionRange: "39,044 - 39,220",
  },
  {
    symbol: "VIX",
    name: "CBOE Volatility Index",
    price: 14.2,
    displayValue: "14.20",
    change: -0.61,
    displayChange: "-0.61",
    changePercent: -4.12,
    sessionRange: "13.9 - 15.4",
  },
  {
    symbol: "TNX",
    name: "US 10Y Yield",
    price: 4.09,
    displayValue: "4.09%",
    change: 0.03,
    displayChange: "+0.03",
    changePercent: 0.74,
    sessionRange: "4.04 - 4.11",
  },
];

export const stockProfiles: StockProfile[] = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 192.4,
    change: 2.31,
    changePercent: 1.22,
    marketCap: 2_940_000_000_000,
    sector: "Technology",
    industry: "Consumer Electronics",
    exchange: "NASDAQ",
    peRatio: 29.2,
    dividendYield: 0.47,
    week52Low: 164.08,
    week52High: 199.62,
    volume: 58_400_000,
    averageVolume: 61_200_000,
    beta: 1.18,
    description:
      "Apple designs consumer hardware, software, and a high-margin services ecosystem centered on the iPhone.",
    thesis:
      "Services durability and an ongoing device refresh cycle keep Apple positioned as a steady large-cap compounder.",
    chart: series([184.6, 185.3, 186.1, 187.4, 186.9, 188.2, 189.7, 190.4, 191.1, 191.8, 192.2, 192.4]),
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corp.",
    price: 428.1,
    change: -2.58,
    changePercent: -0.6,
    marketCap: 3_180_000_000_000,
    sector: "Technology",
    industry: "Software Infrastructure",
    exchange: "NASDAQ",
    peRatio: 35.6,
    dividendYield: 0.74,
    week52Low: 334.69,
    week52High: 433.6,
    volume: 22_300_000,
    averageVolume: 24_100_000,
    beta: 0.9,
    description:
      "Microsoft spans cloud infrastructure, enterprise software, cybersecurity, and productivity tools.",
    thesis:
      "Azure growth and Copilot monetization keep Microsoft at the center of enterprise AI spending.",
    chart: series([431.3, 430.8, 430.2, 429.6, 428.9, 429.1, 428.7, 428.5, 428.3, 428.2, 428.1, 428.1]),
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corp.",
    price: 942.7,
    change: 43.12,
    changePercent: 4.79,
    marketCap: 2_360_000_000_000,
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    peRatio: 56.8,
    dividendYield: 0.02,
    week52Low: 390.1,
    week52High: 974.0,
    volume: 49_200_000,
    averageVolume: 53_400_000,
    beta: 1.73,
    description:
      "NVIDIA leads accelerated computing through GPUs, AI infrastructure, and a broad software moat.",
    thesis:
      "Investor appetite remains tied to AI infrastructure demand, hyperscaler capex, and gross margin durability.",
    chart: series([872.3, 878.5, 885.8, 891.1, 899.6, 907.8, 915.4, 924.6, 930.2, 936.9, 940.1, 942.7]),
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    price: 171.2,
    change: -5.48,
    changePercent: -3.1,
    marketCap: 544_000_000_000,
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    exchange: "NASDAQ",
    peRatio: 49.3,
    dividendYield: 0,
    week52Low: 152.37,
    week52High: 278.98,
    volume: 104_600_000,
    averageVolume: 112_300_000,
    beta: 2.05,
    description:
      "Tesla builds EVs, energy products, and autonomy software while remaining one of the market's highest-beta megacaps.",
    thesis:
      "Margins, deliveries, and autonomy narrative shifts still dominate the stock's near-term volatility.",
    chart: series([178.9, 178.1, 177.4, 176.6, 175.8, 175.2, 174.4, 173.3, 172.9, 172.4, 171.8, 171.2]),
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    price: 181.05,
    change: 1.61,
    changePercent: 0.9,
    marketCap: 1_890_000_000_000,
    sector: "Consumer Cyclical",
    industry: "Internet Retail",
    exchange: "NASDAQ",
    peRatio: 45.4,
    dividendYield: 0,
    week52Low: 118.35,
    week52High: 184.0,
    volume: 33_900_000,
    averageVolume: 37_800_000,
    beta: 1.23,
    description:
      "Amazon combines e-commerce logistics, AWS infrastructure, and a fast-growing advertising business.",
    thesis:
      "Retail margin improvement plus cloud demand keeps Amazon positioned for operating leverage expansion.",
    chart: series([176.2, 176.9, 177.4, 177.8, 178.6, 179.2, 179.8, 180.1, 180.4, 180.6, 180.9, 181.05]),
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    price: 171.88,
    change: 0.54,
    changePercent: 0.32,
    marketCap: 2_120_000_000_000,
    sector: "Communication Services",
    industry: "Internet Content & Information",
    exchange: "NASDAQ",
    peRatio: 27.7,
    dividendYield: 0.43,
    week52Low: 121.46,
    week52High: 174.71,
    volume: 19_800_000,
    averageVolume: 23_500_000,
    beta: 1.04,
    description:
      "Alphabet operates Google Search, YouTube, cloud services, and a broad portfolio of AI models and tools.",
    thesis:
      "Search monetization stability and Gemini commercialization remain the two most watched levers.",
    chart: series([168.3, 168.7, 169.1, 169.5, 170.1, 170.6, 170.9, 171.0, 171.3, 171.5, 171.7, 171.88]),
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    price: 198.42,
    change: 1.72,
    changePercent: 0.87,
    marketCap: 568_000_000_000,
    sector: "Financial Services",
    industry: "Banks - Diversified",
    exchange: "NYSE",
    peRatio: 12.8,
    dividendYield: 2.25,
    week52Low: 135.19,
    week52High: 200.94,
    volume: 8_900_000,
    averageVolume: 9_200_000,
    beta: 1.08,
    description:
      "JPMorgan is a leading global bank with broad exposure across consumer banking, credit cards, markets, and asset management.",
    thesis:
      "Higher-for-longer rates still help net interest income, but credit quality is the key watch item.",
    chart: series([193.6, 194.1, 194.7, 195.4, 196.2, 196.8, 197.3, 197.6, 197.9, 198.0, 198.2, 198.42]),
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    price: 278.74,
    change: 2.86,
    changePercent: 1.04,
    marketCap: 571_000_000_000,
    sector: "Financial Services",
    industry: "Credit Services",
    exchange: "NYSE",
    peRatio: 31.4,
    dividendYield: 0.82,
    week52Low: 227.68,
    week52High: 281.45,
    volume: 6_800_000,
    averageVolume: 7_100_000,
    beta: 0.95,
    description:
      "Visa operates a global payments network with strong free cash flow and structurally attractive margins.",
    thesis:
      "Cross-border volume recovery and steady payment digitization support a durable compounding setup.",
    chart: series([269.6, 270.4, 271.3, 272.1, 273.6, 274.8, 275.9, 276.8, 277.3, 277.9, 278.3, 278.74]),
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    price: 184.27,
    change: 4.34,
    changePercent: 2.41,
    marketCap: 297_000_000_000,
    sector: "Technology",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    peRatio: 48.2,
    dividendYield: 0,
    week52Low: 93.12,
    week52High: 187.28,
    volume: 62_100_000,
    averageVolume: 66_200_000,
    beta: 1.71,
    description:
      "AMD competes across CPUs, data center accelerators, and gaming silicon with growing AI optionality.",
    thesis:
      "Execution against enterprise accelerator demand is the main variable driving multiple expansion.",
    chart: series([173.2, 174.1, 175.5, 176.9, 177.8, 178.9, 180.4, 181.8, 182.6, 183.2, 183.9, 184.27]),
  },
  {
    symbol: "META",
    name: "Meta Platforms Inc.",
    price: 502.16,
    change: 9.34,
    changePercent: 1.9,
    marketCap: 1_290_000_000_000,
    sector: "Communication Services",
    industry: "Internet Content & Information",
    exchange: "NASDAQ",
    peRatio: 29.8,
    dividendYield: 0.39,
    week52Low: 274.38,
    week52High: 509.51,
    volume: 13_100_000,
    averageVolume: 15_200_000,
    beta: 1.21,
    description:
      "Meta operates large-scale social platforms, ad systems, messaging, and a growing AI distribution layer.",
    thesis:
      "Advertising efficiency plus AI-powered engagement gains continue to offset ongoing Reality Labs investment.",
    chart: series([484.8, 486.1, 488.2, 490.7, 492.5, 494.3, 496.8, 498.1, 499.4, 500.2, 501.5, 502.16]),
  },
  {
    symbol: "GOOG",
    name: "Alphabet Inc.",
    price: 298.79,
    change: -6.94,
    changePercent: -2.27,
    marketCap: 2_120_000_000_000,
    sector: "Communication Services",
    industry: "Internet Content & Information",
    exchange: "NASDAQ",
    peRatio: 27.7,
    dividendYield: 0.43,
    week52Low: 121.46,
    week52High: 174.71,
    volume: 19_800_000,
    averageVolume: 23_500_000,
    beta: 1.04,
    description:
      "Alphabet operates Google Search, YouTube, cloud services, and a broad portfolio of AI models and tools.",
    thesis:
      "Search monetization stability and Gemini commercialization remain the two most watched levers.",
    chart: series([305.2, 304.1, 302.8, 301.5, 300.2, 299.4, 298.9, 298.5, 298.2, 298.0, 298.79, 298.79]),
  },
  {
    symbol: "SMCI",
    name: "Super Micro Computer, Inc.",
    price: 34.22,
    change: -18.4,
    changePercent: -34.96,
    marketCap: 20_100_000_000,
    sector: "Technology",
    industry: "Computer Hardware",
    exchange: "NASDAQ",
    peRatio: 14.99,
    dividendYield: 0,
    week52Low: 30.12,
    week52High: 69.0,
    volume: 242_960_000,
    averageVolume: 41_000_000,
    beta: 1.85,
    description:
      "Super Micro designs high-performance server and storage systems for data centers and AI infrastructure.",
    thesis:
      "Sentiment is dominated by AI server demand visibility, competitive dynamics, and headline risk around compliance.",
    chart: series([52.6, 49.2, 46.1, 42.8, 40.2, 38.4, 36.9, 35.8, 35.1, 34.6, 34.3, 34.22]),
  },
  {
    symbol: "WELL",
    name: "Welltower Inc.",
    price: 178.42,
    change: -8.12,
    changePercent: -4.36,
    marketCap: 136_650_000_000,
    sector: "Real Estate",
    industry: "REIT - Healthcare Facilities",
    exchange: "NYSE",
    peRatio: 137.92,
    dividendYield: 1.48,
    week52Low: 155.0,
    week52High: 198.0,
    volume: 4_130_000,
    averageVolume: 3_200_000,
    beta: 0.82,
    description:
      "Welltower is a healthcare-focused REIT with a diversified portfolio of senior housing and outpatient assets.",
    thesis:
      "Rate sensitivity and operating trends in healthcare real estate drive near-term relative performance.",
    chart: series([186.5, 185.2, 184.1, 182.9, 181.4, 180.2, 179.6, 178.9, 178.5, 178.3, 178.42, 178.42]),
  },
  {
    symbol: "CMS",
    name: "CMS Energy Corporation",
    price: 62.18,
    change: -1.24,
    changePercent: -1.95,
    marketCap: 22_810_000_000,
    sector: "Utilities",
    industry: "Utilities - Regulated Electric",
    exchange: "NYSE",
    peRatio: 21.14,
    dividendYield: 2.95,
    week52Low: 58.4,
    week52High: 67.2,
    volume: 4_560_000,
    averageVolume: 3_100_000,
    beta: 0.41,
    description:
      "CMS Energy is a regulated electric and gas utility serving Michigan with a growing clean energy investment plan.",
    thesis:
      "Regulatory outcomes, weather-normalized sales, and capex plans frame the earnings trajectory.",
    chart: series([63.4, 63.1, 62.8, 62.6, 62.4, 62.3, 62.2, 62.19, 62.18, 62.18, 62.18, 62.18]),
  },
  {
    symbol: "VST",
    name: "Vistra Corp.",
    price: 142.6,
    change: -9.8,
    changePercent: -6.43,
    marketCap: 49_480_000_000,
    sector: "Utilities",
    industry: "Independent Power Producers",
    exchange: "NYSE",
    peRatio: 66.98,
    dividendYield: 0.62,
    week52Low: 128.0,
    week52High: 168.0,
    volume: 8_610_000,
    averageVolume: 5_200_000,
    beta: 1.12,
    description:
      "Vistra operates power generation and retail electricity across key U.S. markets with growing battery storage exposure.",
    thesis:
      "Power prices, hedging strategy, and balance sheet flexibility remain the key swing factors.",
    chart: series([152.4, 150.1, 148.6, 147.2, 145.8, 144.5, 143.2, 142.9, 142.7, 142.65, 142.6, 142.6]),
  },
  {
    symbol: "MOS",
    name: "The Mosaic Company",
    price: 28.34,
    change: -1.82,
    changePercent: -6.04,
    marketCap: 7_490_000_000,
    sector: "Basic Materials",
    industry: "Agricultural Inputs",
    exchange: "NYSE",
    peRatio: 13.88,
    dividendYield: 3.73,
    week52Low: 24.1,
    week52High: 36.8,
    volume: 16_900_000,
    averageVolume: 9_800_000,
    beta: 1.25,
    description:
      "Mosaic produces phosphate and potash crop nutrients with global distribution and integrated logistics.",
    thesis:
      "Crop prices, input costs, and channel inventories drive fertilizer demand and margin cycles.",
    chart: series([30.2, 29.8, 29.4, 29.0, 28.7, 28.5, 28.42, 28.38, 28.36, 28.35, 28.34, 28.34]),
  },
  {
    symbol: "ANNA",
    name: "AleAnna, Inc.",
    price: 7.07,
    change: 3.28,
    changePercent: 86.54,
    marketCap: 420_000_000,
    sector: "Healthcare",
    industry: "Biotechnology",
    exchange: "NASDAQ",
    peRatio: 0,
    dividendYield: 0,
    week52Low: 2.1,
    week52High: 7.4,
    volume: 58_000_000,
    averageVolume: 12_000_000,
    beta: 2.4,
    description:
      "AleAnna is a clinical-stage biotechnology company developing targeted oncology therapies.",
    thesis:
      "Catalysts around trial readouts and partnership discussions drive liquidity and volatility.",
    chart: series([3.8, 4.2, 4.9, 5.6, 6.1, 6.4, 6.7, 6.85, 6.95, 7.02, 7.05, 7.07]),
  },
  {
    symbol: "ROMA",
    name: "Roma Green Finance Limited",
    price: 6.94,
    change: 1.82,
    changePercent: 35.55,
    marketCap: 190_000_000,
    sector: "Financial Services",
    industry: "Capital Markets",
    exchange: "NASDAQ",
    peRatio: 0,
    dividendYield: 0,
    week52Low: 4.2,
    week52High: 7.1,
    volume: 22_000_000,
    averageVolume: 8_000_000,
    beta: 1.9,
    description:
      "Roma Green Finance provides sustainability-linked financing advisory and capital markets services.",
    thesis:
      "Green finance policy tailwinds compete with small-cap liquidity constraints.",
    chart: series([5.12, 5.35, 5.6, 5.85, 6.05, 6.2, 6.45, 6.6, 6.72, 6.8, 6.88, 6.94]),
  },
  {
    symbol: "CELG-RI",
    name: "Bristol-Myers Squibb Company Ce",
    price: 0.14,
    change: 0.032,
    changePercent: 29.0,
    marketCap: 12_000_000,
    sector: "Healthcare",
    industry: "Drug Manufacturers",
    exchange: "NYSE",
    peRatio: 0,
    dividendYield: 0,
    week52Low: 0.08,
    week52High: 0.19,
    volume: 4_200_000,
    averageVolume: 1_100_000,
    beta: 0.5,
    description:
      "Contingent value right tied to legacy Bristol-Myers Squibb acquisition milestones.",
    thesis:
      "Outcome depends on regulatory and clinical milestone timing.",
    chart: series([0.11, 0.112, 0.115, 0.118, 0.122, 0.126, 0.128, 0.132, 0.135, 0.138, 0.139, 0.14]),
  },
  {
    symbol: "ESUSD",
    name: "E-mini S&P 500 Futures",
    price: 6559.0,
    change: -101.0,
    changePercent: -1.52,
    marketCap: 0,
    sector: "Derivatives",
    industry: "Index Futures",
    exchange: "CME",
    peRatio: 0,
    dividendYield: 0,
    week52Low: 6200,
    week52High: 6800,
    volume: 1_800_000,
    averageVolume: 1_600_000,
    beta: 0,
    description: "E-mini S&P 500 futures track the S&P 500 index with standardized contract sizing.",
    thesis: "Liquidity and macro catalysts drive session-to-session moves.",
    chart: series([6620, 6610, 6595, 6588, 6575, 6568, 6562, 6559, 6559, 6559, 6559, 6559]),
  },
  {
    symbol: "NQUSD",
    name: "E-mini NASDAQ-100 Futures",
    price: 24101.5,
    change: -478.5,
    changePercent: -1.95,
    marketCap: 0,
    sector: "Derivatives",
    industry: "Index Futures",
    exchange: "CME",
    peRatio: 0,
    dividendYield: 0,
    week52Low: 23000,
    week52High: 25200,
    volume: 900_000,
    averageVolume: 850_000,
    beta: 0,
    description: "E-mini NASDAQ-100 futures provide exposure to the Nasdaq-100 index.",
    thesis: "Tech-heavy positioning amplifies moves versus broad benchmarks.",
    chart: series([24580, 24520, 24440, 24360, 24280, 24200, 24140, 24101.5, 24101.5, 24101.5, 24101.5, 24101.5]),
  },
  {
    symbol: "YMUSD",
    name: "E-mini Dow Futures",
    price: 45893.0,
    change: -448.0,
    changePercent: -0.97,
    marketCap: 0,
    sector: "Derivatives",
    industry: "Index Futures",
    exchange: "CBOT",
    peRatio: 0,
    dividendYield: 0,
    week52Low: 44000,
    week52High: 47200,
    volume: 120_000,
    averageVolume: 110_000,
    beta: 0,
    description: "E-mini Dow futures track the Dow Jones Industrial Average.",
    thesis: "Price-weighted composition can diverge meaningfully from cap-weighted indices.",
    chart: series([46340, 46280, 46180, 46080, 45980, 45920, 45893, 45893, 45893, 45893, 45893, 45893]),
  },
  {
    symbol: "VIX",
    name: "CBOE Volatility Index",
    price: 26.78,
    change: 2.72,
    changePercent: 11.31,
    marketCap: 0,
    sector: "Indices",
    industry: "Volatility",
    exchange: "CBOE",
    peRatio: 0,
    dividendYield: 0,
    week52Low: 11.2,
    week52High: 32.4,
    volume: 0,
    averageVolume: 0,
    beta: 0,
    description:
      "The VIX index reflects market expectations for near-term volatility implied by S&P 500 index options.",
    thesis: "Spikes often coincide with risk-off episodes and macro uncertainty.",
    chart: series([24.1, 24.4, 24.9, 25.2, 25.6, 26.0, 26.4, 26.78, 26.78, 26.78, 26.78, 26.78]),
  },
  {
    symbol: "CURV",
    name: "Torrid Holdings Inc.",
    price: 1.6,
    change: 0.35,
    changePercent: 28.0,
    marketCap: 180_000_000,
    sector: "Consumer Cyclical",
    industry: "Apparel Retail",
    exchange: "NYSE",
    peRatio: 8.2,
    dividendYield: 0,
    week52Low: 1.05,
    week52High: 2.4,
    volume: 9_800_000,
    averageVolume: 4_200_000,
    beta: 1.6,
    description:
      "Torrid is a specialty retailer focused on plus-size women's apparel and accessories.",
    thesis:
      "Margin recovery and inventory discipline are the main levers investors are watching.",
    chart: series([1.25, 1.28, 1.32, 1.35, 1.38, 1.41, 1.44, 1.47, 1.52, 1.55, 1.58, 1.6]),
  },
  ...listedInstruments(),
];

export const topMovers: TopMover[] = [
  {
    symbol: "NVDA",
    name: "NVIDIA Corp.",
    price: 942.7,
    changePercent: 4.79,
    narrative: "AI infrastructure names remain the leadership pocket as hyperscaler capex expectations stay elevated.",
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    price: 184.27,
    changePercent: 2.41,
    narrative: "Semis are catching sympathy bids after strong enterprise accelerator channel checks.",
  },
  {
    symbol: "META",
    name: "Meta Platforms Inc.",
    price: 502.16,
    changePercent: 1.9,
    narrative: "Digital ad sentiment is firming as platform monetization execution stays consistent.",
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    price: 171.2,
    changePercent: -3.1,
    narrative: "Delivery and margin uncertainty continue to pull the stock around more than the wider market.",
  },
];

export const sectorPerformance: SectorPerformance[] = [
  {
    name: "Semiconductors",
    changePercent: 2.18,
    leaders: ["NVDA", "AMD"],
  },
  {
    name: "Financial Services",
    changePercent: 0.94,
    leaders: ["JPM", "V"],
  },
  {
    name: "Consumer Cyclical",
    changePercent: -0.62,
    leaders: ["AMZN", "TSLA"],
  },
  {
    name: "Communication Services",
    changePercent: 0.51,
    leaders: ["META", "GOOGL"],
  },
];

export const newsArticles: NewsArticle[] = [
  {
    id: "news-1",
    headline: "Chip rally extends as enterprise AI budgets remain sticky",
    source: "Market Thread",
    publishedAt: "2h ago",
    summary:
      "Semiconductor names outperformed after another round of commentary pointed to durable training and inference demand.",
    url: "https://example.com/news/chip-rally",
    relatedSymbols: ["NVDA", "AMD", "MSFT"],
    sentiment: "positive",
  },
  {
    id: "news-2",
    headline: "Mega-cap tech leads index gains while defensives lag",
    source: "Open Tape",
    publishedAt: "3h ago",
    summary:
      "Breadth improved into the afternoon session, although leadership remained concentrated in the largest growth names.",
    url: "https://example.com/news/megacap-tech",
    relatedSymbols: ["AAPL", "MSFT", "GOOGL", "META"],
    sentiment: "neutral",
  },
  {
    id: "news-3",
    headline: "Consumer resilience keeps card networks in focus",
    source: "Street Ledger",
    publishedAt: "5h ago",
    summary:
      "Payments investors continue watching travel and cross-border spend as signs of healthy consumer activity persist.",
    url: "https://example.com/news/card-networks",
    relatedSymbols: ["V", "JPM"],
    sentiment: "positive",
  },
  {
    id: "news-4",
    headline: "EV pricing pressure revives margin concerns",
    source: "Daily Markets",
    publishedAt: "6h ago",
    summary:
      "Auto makers tied to the EV cycle traded lower as investors debated how much room remains for promotional activity.",
    url: "https://example.com/news/ev-pricing",
    relatedSymbols: ["TSLA"],
    sentiment: "negative",
  },
  {
    id: "news-5",
    headline: "Cloud platform demand remains healthy, but guidance matters",
    source: "Exchange Brief",
    publishedAt: "8h ago",
    summary:
      "Infrastructure software and cloud leaders traded in a narrow range while investors reset expectations around next-quarter commentary.",
    url: "https://example.com/news/cloud-guidance",
    relatedSymbols: ["MSFT", "AMZN", "GOOGL"],
    sentiment: "neutral",
  },
];

export const watchlistSymbols = ["AAPL", "MSFT", "NVDA", "JPM", "V", "TSLA"];

export const portfolioHoldings: Holding[] = [
  {
    symbol: "AAPL",
    shares: 48,
    averageCost: 172.12,
  },
  {
    symbol: "MSFT",
    shares: 18,
    averageCost: 386.55,
  },
  {
    symbol: "NVDA",
    shares: 7,
    averageCost: 694.2,
  },
  {
    symbol: "JPM",
    shares: 32,
    averageCost: 168.4,
  },
  {
    symbol: "V",
    shares: 21,
    averageCost: 246.8,
  },
];

export const portfolioTrend = [
  { label: "Oct", value: 82_140 },
  { label: "Nov", value: 89_360 },
  { label: "Dec", value: 94_820 },
  { label: "Jan", value: 101_740 },
  { label: "Feb", value: 108_520 },
  { label: "Mar", value: 124_320 },
];

export const marketPulse: MarketPulse = {
  marketStatus: "US markets · after-hours",
  advancers: 1824,
  decliners: 3171,
  putCallRatio: 1.12,
  fearGreedScore: 28,
};

export const topFutures: FuturesAsset[] = [
  {
    symbol: "ESUSD",
    label: "S&P Futures",
    changePercent: -1.52,
    price: 6559.0,
    change: -101.0,
    sparkline: [0.94, 0.91, 0.89, 0.87, 0.85, 0.82, 0.8, 0.78, 0.76, 0.74, 0.72, 0.7],
    fallbackHref: "/",
  },
  {
    symbol: "NQUSD",
    label: "NASDAQ Fut.",
    changePercent: -1.95,
    price: 24101.5,
    change: -478.5,
    sparkline: [0.96, 0.92, 0.88, 0.85, 0.82, 0.78, 0.75, 0.72, 0.69, 0.66, 0.64, 0.62],
    fallbackHref: "/",
  },
  {
    symbol: "YMUSD",
    label: "Dow Futures",
    changePercent: -0.97,
    price: 45893.0,
    change: -448.0,
    sparkline: [0.93, 0.9, 0.88, 0.86, 0.84, 0.82, 0.8, 0.78, 0.77, 0.75, 0.74, 0.73],
    fallbackHref: "/",
  },
  {
    symbol: "VIX",
    label: "VIX",
    changePercent: 11.31,
    price: 26.78,
    change: 2.72,
    sparkline: [0.45, 0.5, 0.52, 0.55, 0.58, 0.62, 0.66, 0.7, 0.74, 0.78, 0.82, 0.88],
    fallbackHref: "/",
  },
];

export const marketSummaryBlock: MarketSummaryBlock = {
  headline: "Crude Oil Surges +2.80% to $98.23 as Middle East War Enters Fourth Week",
  bullets: [
    'U.S. President Trump issued a 48-hour ultimatum to Iran on Saturday, threatening to "obliterate" Iranian power plants if the Strait of Hormuz is not fully reopened. Iran responded Sunday by warning it would strike U.S.-affiliated energy and desalination infrastructure in the Gulf, sending oil prices to their highest levels in nearly four years, with Brent crude settling at $112.19 per barrel.',
    "U.S. Equity Markets Post Fourth Consecutive Week of Losses",
    "Federal Reserve Signals Extended Pause — or Possible Rate Hike",
    'Nvidia and Micron Sell Off as AI Enters "Show Me" Phase',
    'Tesla\'s Musk Announces "Terafab" In-House Chip Manufacturing Initiative',
    "Bitcoin Slips -1.05% to $68,188 Amid Broader Risk-Off Sentiment",
  ],
  sourceCount: 33,
  updatedLabel: "Updated 2 minutes ago",
};

export const recentDevelopments: RecentDevelopment[] = [
  {
    id: "dev-1",
    timeAgo: "59 minutes ago",
    title: "Major Indices Slide Amid Geopolitical Inflation Fears",
    excerpt:
      "U.S. equities posted broad declines on March 22, with the S&P 500 down 1.43%, the Nasdaq off 1.85%, and the Dow losing roughly 1%. Rising inflation concerns tied to Middle East tensions continued to weigh on investor sentiment.",
  },
  {
    id: "dev-2",
    timeAgo: "20 hours ago",
    title: "Brent Crude Tops $109 as Bond Yields Stay Elevated",
    excerpt:
      "Brent crude traded at $109.55 per barrel on Sunday, pressuring global fixed-income markets. Bond yields remain near multi-month highs as sustained energy costs complicate the case for near-term central bank rate reductions.",
  },
  {
    id: "dev-3",
    timeAgo: "20 hours ago",
    title: "Gold Holds Near $4,576 Entering New Trading Week",
    excerpt:
      "COMEX gold settled at $4,576.30 per ounce, edging up 0.13% on Sunday. Investors are repositioning ahead of a week expected to bring heightened volatility following central bank decisions and ongoing geopolitical uncertainty.",
  },
];

export const popularSpaces: PopularSpace[] = [
  {
    id: "space-sec",
    title: "SEC Findings",
    description: "Analyze fundraising rounds and regulatory documents using SEC findings.",
    cta: "Analyze rounds",
    href: "/research",
  },
  {
    id: "space-buffett",
    title: "What would Buffett say?",
    description:
      "Get answers from Buffett shareholder letters and Berkshire Hathaway's website.",
    cta: "Ask Buffett",
    href: "/compare",
  },
  {
    id: "space-transcripts",
    title: "S&P 500 Transcripts",
    description: "Query any S&P company transcript over the last two years.",
    cta: "Search transcripts",
    href: "/research",
  },
];

export const standouts: StandoutStock[] = [
  {
    symbol: "SMCI",
    name: "Super Micro Computer, Inc.",
    exchange: "NASDAQ",
    volume: 242_960_000,
    marketCap: 12_300_000_000,
    peRatio: 14.99,
    dividendYield: null,
    narrative:
      "SMCI stock crashed over a third of its value in a single session after federal prosecutors issued an indictment targeting co-founder Yishan \"Wally\" Liang over an alleged $2.5 billion scheme to smuggle restricted Nvidia-powered AI servers into China, triggering panic selling and a volume surge of nearly 600% above normal levels.",
  },
  {
    symbol: "WELL",
    name: "Welltower Inc.",
    exchange: "NYSE",
    volume: 4_130_000,
    marketCap: 136_650_000_000,
    peRatio: 137.92,
    dividendYield: 1.48,
    narrative:
      "Welltower (WELL) shares fell sharply after reporting full-year 2025 results that disappointed investors, with the stock declining alongside a broader market pullback driven by escalating Middle East tensions, surging oil prices, and growing inflation concerns weighing on rate-sensitive real estate investment trusts.",
  },
  {
    symbol: "CMS",
    name: "CMS Energy Corporation",
    exchange: "NYSE",
    volume: 4_560_000,
    marketCap: 22_810_000_000,
    peRatio: 21.14,
    dividendYield: 2.95,
    narrative:
      "CMS Energy (NYSE: CMS) shares declined as broader utility sector selling pressure weighed on the stock, with insider share sales by multiple executives in recent weeks and a Wells Fargo price target cut to below current levels dampening investor sentiment, pushing the stock back toward its moving average support.",
  },
  {
    symbol: "VST",
    name: "Vistra Corp.",
    exchange: "NYSE",
    volume: 8_610_000,
    marketCap: 49_480_000_000,
    peRatio: 66.98,
    dividendYield: 0.62,
    narrative:
      "Vistra's stock dropped sharply amid a broad market selloff driven by the ongoing Iran conflict, rising oil prices fueling inflation fears, and renewed concerns over potential Fed rate hikes, compounding existing headwinds from the company's recent earnings miss and post-ex-dividend selling pressure.",
  },
  {
    symbol: "MOS",
    name: "The Mosaic Company",
    exchange: "NYSE",
    volume: 16_900_000,
    marketCap: 7_490_000_000,
    peRatio: 13.88,
    dividendYield: 3.73,
    narrative:
      "Mosaic (MOS) shares fell sharply as surging oil prices driven by the Strait of Hormuz crisis and the U.S.-Israeli strikes on Iran raised input and transportation costs for fertilizer production while simultaneously stoking fears of a broader economic slowdown that would weaken agricultural commodity demand.",
  },
];

function watchlistFromProfiles(symbols: string[]): WatchlistBarEntry[] {
  return symbols
    .map((sym) => stockProfiles.find((profile) => profile.symbol === sym))
    .filter((value): value is StockProfile => Boolean(value))
    .map((stock) => ({
      symbol: stock.symbol,
      name: stock.name,
      price: stock.price,
      changePercent: stock.changePercent,
      exchange: stock.exchange,
    }));
}

export const watchlistBarEntries = watchlistFromProfiles([
  "NVDA",
  "V",
  "AMZN",
  "AAPL",
  "GOOG",
]);

export const marketMoversLists: MarketMovers = {
  gainers: [
    { symbol: "ANNA", name: "AleAnna, Inc.", price: 7.07, changePercent: 86.54, exchange: "NASDAQ" },
    { symbol: "ROMA", name: "Roma Green Finance Limited", price: 6.94, changePercent: 35.55, exchange: "NASDAQ" },
    { symbol: "CELG-RI", name: "Bristol-Myers Squibb Company Ce", price: 0.14, changePercent: 29.0, exchange: "NYSE" },
    { symbol: "CURV", name: "Torrid Holdings Inc.", price: 1.6, changePercent: 28.0, exchange: "NYSE" },
  ],
  losers: [
    { symbol: "SMCI", name: "Super Micro Computer, Inc.", price: 34.22, changePercent: -34.96, exchange: "NASDAQ" },
    { symbol: "VST", name: "Vistra Corp.", price: 142.6, changePercent: -6.43, exchange: "NYSE" },
    { symbol: "MOS", name: "The Mosaic Company", price: 28.34, changePercent: -6.04, exchange: "NYSE" },
    { symbol: "TSLA", name: "Tesla Inc.", price: 171.2, changePercent: -3.1, exchange: "NASDAQ" },
  ],
  active: [
    { symbol: "NVDA", name: "NVIDIA Corp.", price: 942.7, changePercent: 4.79, exchange: "NASDAQ" },
    { symbol: "SMCI", name: "Super Micro Computer, Inc.", price: 34.22, changePercent: -34.96, exchange: "NASDAQ" },
    { symbol: "AMD", name: "Advanced Micro Devices", price: 184.27, changePercent: 2.41, exchange: "NASDAQ" },
    { symbol: "TSLA", name: "Tesla Inc.", price: 171.2, changePercent: -3.1, exchange: "NASDAQ" },
  ],
};

export const equitySectorEtfs: SectorEtfRow[] = [
  { name: "Technology", symbol: "XLK", price: 135.29, changePercent: -2.27 },
  { name: "Energy", symbol: "XLE", price: 59.31, changePercent: -0.08 },
  { name: "Consumer Cyclical", symbol: "XLY", price: 107.74, changePercent: -1.79 },
  { name: "Consumer Defensive", symbol: "XLP", price: 81.29, changePercent: -0.83 },
  { name: "Communication Services", symbol: "XLC", price: 112.23, changePercent: -0.8 },
  { name: "Industrials", symbol: "XLI", price: 161.67, changePercent: -1.46 },
  { name: "Financial Services", symbol: "XLF", price: 49.08, changePercent: -0.18 },
  { name: "Utilities", symbol: "XLU", price: 44.65, changePercent: -4.06 },
  { name: "Basic Materials", symbol: "XLB", price: 46.98, changePercent: -1.59 },
  { name: "Real Estate", symbol: "XLRE", price: 40.59, changePercent: -3.17 },
  { name: "Healthcare", symbol: "XLV", price: 145.33, changePercent: -0.87 },
];

export const cryptoQuotes: CryptoQuote[] = [
  { name: "Bitcoin", symbol: "BTCUSD", pairLabel: "BTCUSD · CRYPTO", price: 68_292, changePercent: -2.96 },
  { name: "Ethereum", symbol: "ETHUSD", pairLabel: "ETHUSD · CRYPTO", price: 2066.8, changePercent: -3.96 },
  { name: "Solana", symbol: "SOLUSD", pairLabel: "SOLUSD · CRYPTO", price: 87.05, changePercent: -3.07 },
  { name: "XRP", symbol: "XRPUSD", pairLabel: "XRPUSD · CRYPTO", price: 1.39, changePercent: -3.38 },
];

export const fixedIncomeRows: FixedIncomeRow[] = [
  { name: "T.I.P.S.", symbol: "TIP", price: 110.22, changePercent: -0.8 },
  { name: "U.S. Treasuries", symbol: "GOVT", price: 22.79, changePercent: -0.72 },
  { name: "Municipals", symbol: "MUB", price: 105.91, changePercent: -0.88 },
  { name: "Convertibles", symbol: "CWB", price: 91.98, changePercent: -2.26 },
  { name: "High Yield", symbol: "HYG", price: 78.92, changePercent: -0.93 },
  { name: "High Grade", symbol: "LQD", price: 107.85, changePercent: -1.23 },
];
